# FIPS Code Mappings and Region Definitions

metadata:
  description: "FIPS code mappings and region definitions for coastal counties analysis"
  last_updated: "2024-02-06"

# Region definitions with state FIPS codes and map bounds
regions:
  Northeast:
    states: ['09', '23', '25', '33', '34', '36', '44', '50']  # CT, ME, MA, NH, NJ, NY, RI, VT
    bounds:
      minx: -76
      miny: 40
      maxx: -66
      maxy: 48
  Southeast:
    states: ['10', '11', '12', '13', '24', '37', '45', '51', '54']  # DE, DC, FL, GA, MD, NC, SC, VA, WV
    bounds:
      minx: -85
      miny: 24
      maxx: -75
      maxy: 40
  Gulf Coast:
    states: ['01', '22', '28', '48']  # AL, LA, MS, TX
    bounds:
      minx: -98
      miny: 25
      maxx: -80
      maxy: 35
  Pacific:
    states: ['02', '06', '41', '53']  # AK, CA, OR, WA
    bounds:
      minx: -180
      miny: 30
      maxx: -115
      maxy: 72
  Pacific Islands:
    states: ['15']  # HI
    bounds:
      minx: -160
      miny: 18
      maxx: -154
      maxy: 23
  Caribbean:
    states: ['72']  # PR
    bounds:
      minx: -68
      miny: 17
      maxx: -65
      maxy: 19

# State FIPS to name mapping
state_names:
  '01': 'Alabama'
  '02': 'Alaska'
  '04': 'Arizona'
  '05': 'Arkansas'
  '06': 'California'
  '08': 'Colorado'
  '09': 'Connecticut'
  '10': 'Delaware'
  '11': 'District of Columbia'
  '12': 'Florida'
  '13': 'Georgia'
  '15': 'Hawaii'
  '16': 'Idaho'
  '17': 'Illinois'
  '18': 'Indiana'
  '19': 'Iowa'
  '20': 'Kansas'
  '21': 'Kentucky'
  '22': 'Louisiana'
  '23': 'Maine'
  '24': 'Maryland'
  '25': 'Massachusetts'
  '26': 'Michigan'
  '27': 'Minnesota'
  '28': 'Mississippi'
  '29': 'Missouri'
  '30': 'Montana'
  '31': 'Nebraska'
  '32': 'Nevada'
  '33': 'New Hampshire'
  '34': 'New Jersey'
  '35': 'New Mexico'
  '36': 'New York'
  '37': 'North Carolina'
  '38': 'North Dakota'
  '39': 'Ohio'
  '40': 'Oklahoma'
  '41': 'Oregon'
  '42': 'Pennsylvania'
  '44': 'Rhode Island'
  '45': 'South Carolina'
  '46': 'South Dakota'
  '47': 'Tennessee'
  '48': 'Texas'
  '49': 'Utah'
  '50': 'Vermont'
  '51': 'Virginia'
  '53': 'Washington'
  '54': 'West Virginia'
  '55': 'Wisconsin'
  '56': 'Wyoming'
  '60': 'American Samoa'
  '66': 'Guam'
  '69': 'Northern Mariana Islands'
  '72': 'Puerto Rico'
  '78': 'U.S. Virgin Islands'

# FIPS code field mappings
field_mappings:
  county_fips:
    - STATEFP  # First field
    - COUNTYFP  # Second field
  state_fips: STATEFP 