earth_engine:
  project_id: ee-chrismihiar
  model: ACCESS-CM2
  image_collection: NASA/GDDP-CMIP6
  variable: tas

climate:
  scenario: ssp585
  variables:
    - tas
    - pr

data:
  years:
    start: 2020
    end: 2022
  dir: data

output:
  dir: output

processing:
  chunk_size: 10000
  max_concurrent_tasks: 3000